version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/kafka

  postgres:
    image: postgres
    container_name: dvt-pg
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dvt
    volumes:
      - dvt-pg:/var/lib/postgresql/data

  video-service:
    build: ./video-service
    container_name: video-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka:9092
      - KAFKA_TOPIC=video
      - PORT=:8080
      - DB_SOURCE=postgres://postgres:postgres@postgres:5432/dvt?sslmode=disable

  transcoder-worker:
    build: ./transcoder-worker
    ports:
      - "8081"
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka:9092
      - KAFKA_TOPIC=video
      - PORT=:8081
      - VIDEO_SERVICE_ADDRESS=http://video-service:8080
    deploy:
      replicas: 3

volumes:
  dvt-pg:
  kafka-data:
